parionsport:
  philosophy: link # or link
  home_page: https://www.enligne.parionssport.fdj.fr
  absolute_url: False
  tags_chamionship:
    sport: //li[@class="psel-quicknav__item"]
    sport_name:  //span[@pselautotestid="quick_nav_ept_sport_lbl"]/text()
    country_name:  .//span[@pselautotestid="quick_nav_ept_category_lbl"]//text()
    country : .//psel-ept-competitions
    championship:  .//a[@pseltcclick="quickaccess_eptCompetition"]//@href
    championship_name: .//a[@pseltcclick="quickaccess_eptCompetition"]//text()
  tags_button:
    bet_filter: .//button[@class="psel-filters__label" and contains(., "1 N 2") and not(contains(., "Handicap"))]
    cookies: .//button[@id="popin_tc_privacy_button_2"]
  tags_odd: 
    date : //h2[@class="psel-title-rubric__text"]
    bloc_match: .//psel-event-main
    date_hours: .//time[@class="psel-timer"]/text() 
    bloc_odd: .//psel-templates
    name_team: .//p[contains(@class,"psel-market")]/text()
    odd:  .//span[@class="psel-outcome__data"]/text()
  data-odd-type:
    - Win
    - Draw
    - Win

betclic :
  philosophy: click # or link
  home_page : https://www.betclic.fr/
  absolute_url : False
  tags_chamionship :
    sport:  //sports-tile[@routerlinkactive="active-link" and  contains(@class,"sportList_item ")] #//a[@class="sportList_itemWrapper" and @id="block-link-null"] #//a[@class="sportList_itemWrapper" and @id="block-link-null"]/div[@class="sportlist_name"]
    sport_name:  //a[@class="sportList_itemWrapper" and @id="block-link-null"]/div[@class="sportlist_name"]/text()
    country_name:  //div[@class="sportList_itemWrapper"]/div[@class="sportlist_name"]/text() 
    country : .//ul//li[@routerlinkactive="active-link"] #.//li[@routerlinkactive="active-link" and @class="sportList_item has-children ng-star-inserted"]
    championship :  //ul[contains(@class,"sportList_listLv2 ")]//div[@class="sportlist_name"]
    championship_name :   //ul[@class="sportList_listLv2 ng-star-inserted"]//div[@class="sportlist_name"]/text()
  tags_button:
    bet_filter:
    cookies: //button[@id="popin_tc_privacy_button_2" and @class="tc-reset-css tc-privacy-button"]
  tags_odd:
    date : //h2[@class="groupEvents_headTitle"]/text()
    bloc_match: //sports-events-event[@class="groupEvents_card ng-star-inserted"] 
    date_hours: .//div[@class="event_infoTime ng-star-inserted"]/text() 
    bloc_odd: //div[@class="market_odds ng-star-inserted"]
    name_team:  //div[contains(@class,"scoreboard_contestantLabel ")]/text()
    odd:  .//span[contains(@class,"oddValue")]/text()
    match: 
  data-odd-type:
    - Win
    - Draw
    - Win

winamax:
  philosophy: link # or link
  home_page: https://www.winamax.fr/paris-sportifs/
  absolute_url: False
  tags_chamionship:
    sport: //a[@class="sc-iBkjds ehkIYx sc-papXJ kEoJqC sc-llJcti hkAQYJ" or @class="sc-iBkjds ehkIYx sc-papXJ dZRYHe sc-llJcti hkAQYJ"]/parent::div[@class="sc-iIPllB ieQLRI"]  #//a[@class="sc-iBkjds ehkIYx sc-papXJ kEoJqC sc-llJcti hkAQYJ" or @class="sc-iBkjds ehkIYx sc-papXJ dZRYHe sc-llJcti hkAQYJ"]
    sport_name:  //div[@class="sc-iIPllB ieQLRI"]//a[@class="sc-iBkjds ehkIYx sc-papXJ kEoJqC sc-llJcti hkAQYJ" or @class="sc-iBkjds ehkIYx sc-papXJ dZRYHe sc-llJcti hkAQYJ"]//text()
    country_name:  .//a[@class="sc-iBkjds ehkIYx sc-papXJ fWNpsq sc-llJcti bCeysP" or @class="sc-iBkjds ehkIYx sc-papXJ bzSATK sc-llJcti bCeysP"]//text()
    country : (.//div[contains(@class, "CollapseListItem-collapse") and .//div[@class="sc-iIPllB ieQLRI"]])[position() > 1] #.//a[@class="sc-iBkjds ehkIYx sc-papXJ fWNpsq sc-llJcti bCeysP" or @class="sc-iBkjds ehkIYx sc-papXJ bzSATK sc-llJcti bCeysP"]
    championship: .//div[@class="sc-iIPllB ieQLRI"]/a/@href #.//a[@class="sc-ftvSup kzqHjm sc-papXJ doVFwd sc-llJcti bCeysV" ]//@href
    championship_name: .//div[@class="sc-iIPllB ieQLRI"]/a/div[@class="sc-jIZahH dmqQpe" or @class="sc-jIZahH gpAtDz"]/text()
  tags_button:
    bet_filter:
    cookies: //button[@class="tarteaucitronCTAButton tarteaucitronAllow"]
  tags_odd: 
    date : //span[@class="sc-geuGuN fOfBwL"]/text()
    bloc_match: .//div[@class="sc-cQQOYb iTbLnN" and not(contains(., "En cours"))] #//div[@class="sc-cQQOYb iTbLnN"]
    date_hours: .//span[@class="sc-geuGuN fOfBwL"]/text() #//span[@class="sc-geuGuN fOfBwL"]/text()
    bloc_odd: .//div[@class="sc-gbrkvF hSTBHh sc-hYYQjs cheNIR"]
    name_team: .//div[@class="sc-cjCnCM iOBsim"]/text() #//div[@class="sc-cjCnCM iOBsim"]/text()
    odd:  .//span[@class="sc-kkhAli cDmPxg"]/text()
  data-odd-type:
    - Win
    - Draw
    - Win

france-pari:
  philosophy: click # or link
  home_page: https://www.france-pari.fr/
  absolute_url: False
  tags_chamionship:
    sport: //li[contains(@class,"title type-sport")]
    sport_name: //li[contains(@class,"type-sport")]//div[contains(@class,"title ")]//span/text()
    country_name:  .//div[@class="menu-element-toggle"]//span/text()
    country : .//li[contains(@class,"title item-category")] #.//li[contains(@class,"title item-category")]
    close_country: .//li[contains(@class,"title item-category")]//div[@class="menu-element-toggle"]
    championship:  //div[@class="uk-accordion-content menu-accordion-content" and @style=""]//ul[@class="type-competition"]
    championship_name: //div[@class="menu-element-without-toggle avoid-close-competition-menu"]//span/text()
  tags_button:
    bet_filter:
    cookies: //button[@class="termly-styles-module-root-f61419 termly-styles-module-primary-9738f2 termly-styles-module-solid-20a66a termly-styles-button-dd5ebb t-acceptAllButton"]
  tags_odd: 
    date : //div[@class="date-event"]//span[1]/text()
    bloc_match: //div[@class="lines"][not(.//div[contains(@class,"isNextHour")])]
    date_hours: .//div[@class="date-event" or @class="date-event event-isLive"]//span/text()
    bloc_odd: //a[contains(@class,"odd vertical centered")]
    name_team: .//div[@class="actors text-ellipsis"]//span/text()
    odd:  .//span[@class="container-odd-and-trend"]/text()
  data-odd-type:
    - Win
    - Draw
    - Win

pinnacle:
  philosophy: click # or link
  home_page: https://www.pinnacle.com/fr/
  absolute_url: False
  tags_chamionship:
    sport: //li[@class="style_listItem__2X9gz undefined"]
    sport_name: //li[@class="style_listItem__2X9gz undefined"]//span//span/text()
    country_name:  
    country:
    go_to_championship_filrer: //a[contains(., 'Championnats')]
    championship:  //div[@class="contentBlock" and not(contains(., 'Principaux championnats'))]//div[contains(@class, "style_supportFavoritesRow")]
    championship_name: //div[@class="contentBlock" and not(contains(., 'Principaux championnats'))]//div[contains(@class, "style_supportFavoritesRow")]//label//text()
  tags_button:
    bet_filter: //button[@id="period:0"]
    cookies: //button[@data-test-id="Button"][contains(., 'Accepter')]
  tags_odd: 
    date : //div[@data-test-id="Events.DateBar"]//text()
    bloc_match: //div[contains(@class, "style_row__3CKCJ style_row__3")]
    date_hours: //div[@class="style_matchupDate__1st0T"]//text()
    bloc_odd: //div[@class="event-wrapper"]
    name_team: .//div[@class="event-wrapper"]//span/text()
    odd:  //div[@class="event-wrapper"]//span/text()
  data-odd-type:
    - Win
    - Draw
    - Win


unibet:
  philosophy: click # or link
  home_page: https://www.unibet.com/betting/sports/home
  absolute_url: False
  tags_chamionship:
    sport: //button[@data-test-name="allSports-sportsItem"]
    sport_name:  //button[@data-test-name="allSports-sportsItem"]//div[contains( @data-test-name,"allSports-sportsItem-sportName")]/text()
    country_name:  //div[@class="_5f930 "]//h3[@class="_4ec65 _12550"]/text() #//a[@nohref="nohref"]//span[@class="label-menu"  and not(contains(., "Tout voir"))]/text()
    country: //div[@class="_5f930 "] #.//li[@class="item-arrow ui-desktop"]/a[@class="linkaction"]
    view : //div[@data-test-name="viewAllLinkWrapper"]
    championship:  //div[@data-test-name="accordionLevel2"]
    championship_name: //div[@class="_5f930 "]//h3[@class="_4ec65 aabf1"]/text()
  tags_button:
    bet_filter:
    cookies: //div/a[@class="ui-button ui-large ui-important link-track"]
  tags_odd: 
    date : //div[@role="button"]//time//text()
    bloc_match: //div[@class="_79bb0"]
    date_hours: .//div[@data-test-name="clockDisplayContainer"]//text()
    bloc_odd: //div[@class="bb419"]
    name_team: //div[@data-test-name="teamName"]//text()
    odd:  //div[@data-test-name="betButtonDisplay" and not(.//div[@data-test-name="oddsHeader"])]//text()   
  data-odd-type:
    - Win
    - Draw
    - Win

unibet.fr:
  philosophy: click # or link
  home_page: https://www.unibet.fr/sport
  absolute_url: False
  tags_chamionship:
    sport: //li[@class="item-arrow"]
    sport_name:  //li[@class="item-arrow"]//span[contains(@class, "label-menu leftside_menu_group_link-label--sportsbook")]/text()
    country_name:  .//li[@class="item-arrow ui-desktop"]//span[@class="label-menu"]/text() #//a[@nohref="nohref"]//span[@class="label-menu"  and not(contains(., "Tout voir"))]/text()
    country: .//li[@class="item-arrow ui-desktop"] #.//li[@class="item-arrow ui-desktop"]/a[@class="linkaction"]
    championship:  //li[@class="sublinks_link"]/a[@class="linkaction" and  not(contains(., "Tout voir"))]
    championship_name: //li[@class="sublinks_link" and  not(contains(., "Tout voir"))]//span[@class="label-menu"]/text()
  tags_button:
    bet_filter:
    cookies: //div/a[@class="ui-button ui-large ui-important link-track"]
  tags_odd: 
    date : //h2[@class="bettingbox-title"]//span[@class="bettingbox-date"]//text()
    bloc_match: //div[@class="ui-mainview-block eventpath-wrapper"]//div[@class="bettingbox-item box"]
    date_hours: .//span[@class="datetime"]//text()
    bloc_odd: //div[@class="cell-market markets table-cell"]
    name_team: //span[@class="odd-label"]//text()
    odd:  .//span[@class="ui-touchlink-needsclick price odd-price"]/text()  
  data-odd-type:
    - Win
    - Draw
    - Win
    
# bet365: 
#   philosophy: click # or link
#   home_page : https://www.bet365.com/
#   absolute_url : False
#   tags_chamionship :
#     sport: //div[@class="wn-PreMatchItem "]/span
#     sport_name: //div[@class="wn-PreMatchItem "]/span/text()
#     group :  //div[@class="sm-SplashMarketGroupButton_Text "]
#     country_name:  
#     championship : //div[@class="sm-SplashMarket_Title "]
#     championship_name : //span[@class="sm-CouponLink_Title "]/text()
#   tags_button:
#     cookies: .//button[@id="popin_tc_privacy_button_2"]
#   tags_odd:
#     bloc_teams_hours_date : //div[@class="rcl-ParticipantFixtureDetails_LhsContainerInner "]
#     name_team : //div[@class="rcl-ParticipantFixtureDetailsTeam_TeamName "]
#     date : //div[@class="rcl-MarketHeaderLabel rcl-MarketHeaderLabel-isdate "]
#     hours : //div[@class="rcl-ParticipantFixtureDetails_BookCloses "]
#     columns_odd :  //div[contains(@class,"MarketOddsExpand")]
#     info_column_which_teams_win :  //div[@class="rcl-MarketColumnHeader "]
#     odd : //span[@class="sgl-ParticipantOddsOnly80_Odds"]
#   data-odd-type:
#     - Win
#     - Draw
#     - Win

# https://www.peopleperhour.com/freelance-jobs/technology-programming/programming-coding/web-scraping-prices-of-insurance-providers-3290248




# https://github.com/migoya2020/bet365-playwright-starter


#//li[@class="psel-quicknav__item"]//li[not(@*)]

#//ul[@class='psel-quicknav__list psel-quicknav__list-level-2']/psel-ept-categories/li[not(@*)]
